version: '2'

services:
  redis:
    container_name: redis
    image: library/redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    command: /bin/sh -c "redis-server --requirepass "$REDIS_PASSWORD""
