version: '2'

services:
  redis:
    image: library/redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - nikola-docker-network

networks:
  nikola-docker-network:
    external: true
