version: '2'

services:
  backend:
    build:
      context: ../../backend
      dockerfile: ./Dockerfile
    ports:
      - '${BACKEND_PORT}:8000'
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    env_file:
      - ../env/.env

  db:
    image: postgres
    env_file: ../env/.env

  redis:
    image: library/redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'

  frontend:
    env_file:
      - ../env/.env
    build:
      context: ../../frontend
      dockerfile: ./Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
